// ─────────────────────────────────────────────────────────────────────────────
//  NDPA Self-Audit Tool — Question Bank
//  28 questions across 5 weighted categories.
//
//  NOTE: Question wording uses sample copy for the wireframe.
//  Final questions must be confirmed and provided by the product owner.
//  Any question lacking final wording should use a neutral placeholder,
//  e.g. "[Question copy to be confirmed]", never "TBD — Question X".
//  See PRD §50 (Unresolved Items).
//
//  Scoring:
//    Yes      = 1
//    Not Sure = 0.5
//    No       = 0
//
//  Category weights (for composite score):
//    Applicability & Awareness   = 15%  (5 questions)
//    Baseline Compliance         = 30%  (7 questions)
//    Lawful Basis & Marketing    = 20%  (5 questions)
//    DPO & Governance            = 10%  (4 questions)
//    Breach Readiness            = 25%  (7 questions)
// ─────────────────────────────────────────────────────────────────────────────

const CATEGORIES = [
  {
    key: "applicability",
    langKey: "applicability",   // maps to LANG[lang].categories.applicability
    weight: 0.15,
    questionCount: 5,
  },
  {
    key: "baseline",
    langKey: "baseline",
    weight: 0.30,
    questionCount: 7,
  },
  {
    key: "lawful",
    langKey: "lawful",
    weight: 0.20,
    questionCount: 5,
  },
  {
    key: "dpo",
    langKey: "dpo",
    weight: 0.10,
    questionCount: 4,
  },
  {
    key: "breach",
    langKey: "breach",
    weight: 0.25,
    questionCount: 7,
  },
];

const QUESTIONS = [
  // ── APPLICABILITY & AWARENESS (Q1–Q5, weight 15%) ────────────────────────
  {
    id: 1,
    category: "applicability",
    text: "Does your business collect any information from customers, like names, phone numbers, addresses, or payment details?",
    textPidgin: "Your business dey collect any information from customers, like their name, phone number, address, or payment details?",
    actionTitle: "Learn about your NDPA obligations",
    actionTitlePidgin: "Learn about wetin NDPA want from your business",
    actionWhy: "Understanding whether and how the NDPA applies to your business is the essential first step to compliance.",
    actionWhyPidgin: "The first step na to understand if NDPA dey apply to your business and wetin e mean for you.",
    actionModule: "Module 1",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 2,
    category: "applicability",
    text: "Do you know what 'personal data' means under the NDPA?",
    textPidgin: "You know wetin NDP Act they call personal data",
    actionTitle: "Understand what counts as personal data",
    actionTitlePidgin: "Understand wetin count as personal data",
    actionWhy: "Personal data includes any information that can identify a person, names, phone numbers, addresses, and more.",
    actionWhyPidgin: "Personal data na any information wey fit identify one person, like name, phone number, address, and plenty more.",
    actionModule: "Module 1",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 3,
    category: "applicability",
    text: "Can you identify all the types of personal data your business currently collects?",
    textPidgin: "You fit identify all the kind personal data wey your business they collect now.",
    actionTitle: "Map the personal data your business holds",
    actionTitlePidgin: "List out the personal data wey your business dey hold",
    actionWhy: "You cannot protect data you don't know you have. A simple data map is the foundation of compliance.",
    actionWhyPidgin: "You no fit protect data wey you no know say you get am. Make simple list of the data you dey collect first.",
    actionModule: "Module 1",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 4,
    category: "applicability",
    text: "Do you understand why your business collects personal data?",
    textPidgin: "You understand why your business dey collect personal data?",
    actionTitle: "Define your purpose for collecting personal data",
    actionTitlePidgin: "Define why your business dey collect personal data",
    actionWhy: "Every piece of personal data you collect should have a clear, documented purpose.",
    actionWhyPidgin: "Every personal data wey you dey collect need get clear reason wey you fit explain.",
    actionModule: "Module 1",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 5,
    category: "applicability",
    text: "Have you reviewed your business practices in the past 12 months for compliance with data protection rules?",
    textPidgin: "You don check your business practices for the last 12 months to see if them align for under NDP Act.",
    actionTitle: "Conduct an annual data protection review",
    actionTitlePidgin: "Check your business every year for data protection",
    actionWhy: "Regular reviews help you catch new risks and keep your practices up to date with any legal changes.",
    actionWhyPidgin: "If you dey check your business often, you go catch new risk early and follow any new law wey come out.",
    actionModule: "Module 1",
    triggeredBy: ["no", "notSure"],
  },

  // ── BASELINE COMPLIANCE (Q6–Q12, weight 30%) ─────────────────────────────
  {
    id: 6,
    category: "baseline",
    text: "Do you have a written privacy notice that tells customers what information you collect and why?",
    textPidgin: "You get written privacy notice wey tell customer which kind information you dey collect and why.",
    actionTitle: "Create a privacy notice for your customers",
    actionTitlePidgin: "Create privacy notice for your customers",
    actionWhy: "Customers should know what information you collect and why you use it. A privacy notice is a legal requirement.",
    actionWhyPidgin: "Customers need know wetin information you dey collect and why you dey use am. Privacy notice na requirement for law.",
    dependsOn: [{ on: 1, showIf: ["yes", "notSure"] }],
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 7,
    category: "baseline",
    text: "Is your privacy notice easy for your customers to find and read?",
    textPidgin: "Your privacy notice easy for customers to find and read?",
    actionTitle: "Make your privacy notice easy to find",
    actionTitlePidgin: "Make your privacy notice easy to find",
    actionWhy: "A privacy notice that customers can't find is as good as not having one.",
    actionWhyPidgin: "Privacy notice wey customers no fit find na like say you no get am at all.",
    dependsOn: [{ on: 1, showIf: ["yes", "notSure"] }],
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 8,
    category: "baseline",
    text: "Do you only collect personal data that you actually need for your business?",
    textPidgin: "You dey collect only the personal data wey your business really need?",
    actionTitle: "Review what data you collect and reduce it where possible",
    actionTitlePidgin: "Check wetin data you dey collect and reduce am",
    actionWhy: "Collecting more data than you need increases your risk and your legal obligations.",
    actionWhyPidgin: "If you dey collect more data than you need, e dey increase your risk and your legal work.",
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 9,
    category: "baseline",
    text: "Do you have a process to delete or anonymise customer data when it is no longer needed?",
    textPidgin: "You get process to delete customer data or remove identity from am when you no need am again?",
    actionTitle: "Set up a data deletion or retention schedule",
    actionTitlePidgin: "Create schedule for how long you go keep data",
    actionWhy: "Holding data longer than necessary increases your risk exposure. You should have a clear policy for when to delete it.",
    actionWhyPidgin: "If you keep data for too long, your risk go increase. You need clear plan for when to delete am.",
    dependsOn: [{ on: 1, showIf: ["yes", "notSure"] }],
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 10,
    category: "baseline",
    text: "Do you keep personal data secure, for example by using passwords, locks, or encryption?",
    textPidgin: "You dey keep personal data safe, like with password, lock, or encryption?",
    actionTitle: "Improve the physical and digital security of customer data",
    actionTitlePidgin: "Make customer data more safe, online and offline",
    actionWhy: "Basic security measures protect your customers and reduce the risk of a data breach.",
    actionWhyPidgin: "Simple security go protect your customers and reduce the chance say person go leak data.",
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 11,
    category: "baseline",
    text: "Do you control who in your business can access customer personal data?",
    textPidgin: "You dey control who inside your business fit see customer personal data?",
    actionTitle: "Restrict access to personal data within your business",
    actionTitlePidgin: "Restrict who fit see personal data for your business",
    actionWhy: "Only staff who need access to personal data for their job should have it.",
    actionWhyPidgin: "Only your staff wey need am for their work suppose get access to personal data.",
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 12,
    category: "baseline",
    text: "Can you respond to a customer who asks to see, correct, or delete their personal data?",
    textPidgin: "You fit answer customer wey ask to see, correct, or delete their personal data?",
    actionTitle: "Put a process in place to handle customer data requests",
    actionTitlePidgin: "Create process for customer data request",
    actionWhy: "Under the NDPA, individuals have rights to access, correct, and delete their data. You must be able to respond.",
    actionWhyPidgin: "Under NDPA, customer get right to see, correct, and delete their data. You must fit answer dem.",
    dependsOn: [{ on: 1, showIf: ["yes", "notSure"] }],
    actionModule: "Module 2",
    triggeredBy: ["no", "notSure"],
  },

  // ── LAWFUL BASIS & MARKETING (Q13–Q17, weight 20%) ───────────────────────
  {
    id: 13,
    category: "lawful",
    text: "When you collect personal data, do you have a clear legal reason for doing so?",
    textPidgin: "When you dey collect personal data, you get clear legal reason for am?",
    actionTitle: "Identify your lawful basis for collecting personal data",
    actionTitlePidgin: "Identify your legal reason for collecting personal data",
    actionWhy: "Every time you collect personal data you need a legal reason, such as consent, a contract, or a legitimate interest.",
    actionWhyPidgin: "Every time you collect personal data, you need legal reason, like consent, contract, or legitimate interest.",
    actionModule: "Module 3",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 14,
    category: "lawful",
    text: "When you rely on consent to collect data, do customers clearly agree before you collect it?",
    textPidgin: "When you dey use consent, customer clearly agree before you collect their data?",
    actionTitle: "Make sure your consent process is clear and freely given",
    actionTitlePidgin: "Make sure customer consent clear and free",
    actionWhy: "Consent must be specific, informed, and freely given. Pre-ticked boxes or buried terms do not count.",
    actionWhyPidgin: "Consent must clear, and customer must know wetin dem dey agree to. No use hidden box or tiny small write-up.",
    actionModule: "Module 3",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 15,
    category: "lawful",
    text: "Does your business send marketing messages to customers through WhatsApp, SMS, or email?",
    textPidgin: "Your business dey send marketing message to customers through WhatsApp, SMS, or email?",
    actionTitle: "Confirm how you send marketing messages and get consent",
    actionTitlePidgin: "Confirm how you dey send marketing message and get consent",
    actionWhy: "Marketing messages need clear consent. Confirm whether and how you send them before continuing.",
    actionWhyPidgin: "Marketing message need clear consent. Confirm whether and how you dey send am before you continue.",
    actionModule: "Module 3",
    triggeredBy: ["notSure"],
  },
  {
    id: 16,
    category: "lawful",
    text: "Do you offer customers an easy way to opt out of marketing messages?",
    textPidgin: "Customer get easy way to stop marketing message wey dem dey receive?",
    actionTitle: "Provide a simple opt-out mechanism for marketing",
    actionTitlePidgin: "Give customer simple way to stop marketing message",
    actionWhy: "Customers must be able to stop receiving marketing messages at any time.",
    actionWhyPidgin: "Customer must fit stop marketing message anytime dem want.",
    dependsOn: [{ on: 15, showIf: ["yes", "notSure"] }],
    actionModule: "Module 3",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 17,
    category: "lawful",
    text: "Do you have a record of when and how customers gave their consent?",
    textPidgin: "You get record of when and how customer give their consent?",
    actionTitle: "Keep records of when customers consented",
    actionTitlePidgin: "Keep record of when customer give consent",
    actionWhy: "If your consent is ever challenged, you need to be able to show evidence of when and how it was given.",
    actionWhyPidgin: "If anybody challenge your consent, you need fit show evidence of when and how e take give am.",
    dependsOn: [{ on: 15, showIf: ["yes", "notSure"] }],
    actionModule: "Module 3",
    triggeredBy: ["no", "notSure"],
  },

  // ── DPO & GOVERNANCE (Q18–Q21, weight 10%) ───────────────────────────────
  {
    id: 18,
    category: "dpo",
    text: "Does your business have someone responsible for data protection, even informally?",
    textPidgin: "Your business get somebody wey dey responsible for data protection, even for small way?",
    actionTitle: "Assign responsibility for data protection in your business",
    actionTitlePidgin: "Put somebody for data protection for your business",
    actionWhy: "Even informally, having one person accountable for data protection makes compliance much easier to manage.",
    actionWhyPidgin: "Even if e be small way, get one person wey dey carry data protection responsibility go make am easier.",
    actionModule: "Module 4",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 19,
    category: "dpo",
    text: "Have you or your staff received any training or guidance on data protection?",
    textPidgin: "You or your staff don receive any training or guidance on data protection?",
    actionTitle: "Train your staff on basic data protection practices",
    actionTitlePidgin: "Train your staff for basic data protection",
    actionWhy: "Your team needs to understand what personal data is, why it matters, and how to handle it safely.",
    actionWhyPidgin: "Your team need understand wetin personal data be, why e matter, and how to handle am safe.",
    actionModule: "Module 4",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 20,
    category: "dpo",
    text: "Do you have any written policies or procedures for handling personal data?",
    textPidgin: "You get any written policy or procedure for handling personal data?",
    actionTitle: "Document your data handling procedures",
    actionTitlePidgin: "Write down how your business dey handle data",
    actionWhy: "Written policies make it easier to ensure consistent, compliant handling of personal data across your business.",
    actionWhyPidgin: "When you write am down, e go easier to make sure say everybody dey handle data well-well.",
    actionModule: "Module 4",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 21,
    category: "dpo",
    text: "If you share personal data with other businesses or contractors, do you have agreements covering data protection?",
    textPidgin: "If you dey share personal data with other business or contractor, you get agreement wey dey cover data protection?",
    actionTitle: "Put data protection agreements in place with third parties",
    actionTitlePidgin: "Put data protection agreement for third party",
    actionWhy: "If you share customer data with others, those parties must also protect it, and you need agreements to confirm this.",
    actionWhyPidgin: "If you dey share customer data with other people, dem must also protect am, and you need agreement to confirm am.",
    actionModule: "Module 4",
    triggeredBy: ["no", "notSure"],
  },

  // ── BREACH READINESS (Q22–Q28, weight 25%) ───────────────────────────────
  {
    id: 22,
    category: "breach",
    text: "Do you know what a personal data breach is?",
    textPidgin: "You know wetin personal data breach be?",
    actionTitle: "Learn what counts as a data breach",
    actionTitlePidgin: "Learn wetin count as data breach",
    actionWhy: "A breach isn't just hacking, it includes accidental loss, wrong delivery, or unauthorised access to personal data.",
    actionWhyPidgin: "Breach no be hacking only, e include when data lost, deliver to wrong person, or person wey no get right see am.",
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 23,
    category: "breach",
    text: "Do you have a plan for what to do if customer data is lost, stolen, or accessed without permission?",
    textPidgin: "You get plan for wetin you go do if customer data lost, dem steal am, or person see am wey no get right?",
    actionTitle: "Create a basic data breach response plan",
    actionTitlePidgin: "Create simple plan for wetin to do when data breach happen",
    actionWhy: "A simple, written plan means you can act quickly and correctly if a breach happens.",
    actionWhyPidgin: "If you get simple plan, you fit act fast and do correct thing when breach happen.",
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 24,
    category: "breach",
    text: "Do you know that you may be required to report a serious data breach to the NDPC?",
    textPidgin: "You know say you fit need report serious data breach to NDPC?",
    actionTitle: "Understand your breach reporting obligations",
    actionTitlePidgin: "Understand wetin you need report for breach",
    actionWhy: "Serious breaches must be reported to the Nigeria Data Protection Commission within 72 hours.",
    actionWhyPidgin: "Serious breach must report to Nigeria Data Protection Commission within 72 hours.",
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 25,
    category: "breach",
    text: "Do you know how you would notify customers if their personal data was involved in a breach?",
    textPidgin: "You know how you go tell customers if their personal data involve for breach?",
    actionTitle: "Plan how you would notify customers after a breach",
    actionTitlePidgin: "Plan how you go inform customers after breach",
    actionWhy: "Affected customers have a right to be informed. You should know in advance how you would contact them.",
    actionWhyPidgin: "Customers wey e affect get right to know. You need know from before how you go reach dem.",
    dependsOn: [{ on: 1, showIf: ["yes", "notSure"] }],
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 26,
    category: "breach",
    text: "Do you keep records of any incidents or near-misses involving personal data?",
    textPidgin: "You dey keep record of any incident or near-miss wey involve personal data?",
    actionTitle: "Start keeping a log of data incidents",
    actionTitlePidgin: "Start recording any data incident",
    actionWhy: "Keeping a record of incidents, even minor ones, helps you spot patterns and demonstrate accountability.",
    actionWhyPidgin: "If you record incidents, even small one, you go fit see pattern and show say you dey accountable.",
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 27,
    category: "breach",
    text: "Have you taken steps to prevent common data security risks, such as weak passwords or unprotected devices?",
    textPidgin: "You don take step to prevent common data security risk, like weak password or phone wey no get protection?",
    actionTitle: "Address common data security vulnerabilities",
    actionTitlePidgin: "Fix common data security problem",
    actionWhy: "Most data breaches are caused by preventable issues, weak passwords, lost devices, and unencrypted data.",
    actionWhyPidgin: "Plenty data breach dey happen because of simple thing, weak password, lost phone, or data wey no encrypt.",
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
  {
    id: 28,
    category: "breach",
    text: "If a data breach happened today, do you feel your business would be able to handle it appropriately?",
    textPidgin: "If data breach happen today, you feel say your business fit handle am well?",
    actionTitle: "Test and improve your breach readiness",
    actionTitlePidgin: "Test and improve how your business fit handle breach",
    actionWhy: "Talking through a hypothetical breach scenario with your team is the best way to find gaps before a real incident.",
    actionWhyPidgin: "If you talk am through with your team before real thing happen, you go fit find the gap.",
    actionModule: "Module 5",
    triggeredBy: ["no", "notSure"],
  },
];

// Scoring constants
const ANSWER_SCORES = {
  yes: 1,
  notSure: 0.5,
  no: 0,
};
